[package]
name = "vslam_tutorial"
version = "0.1.0"
edition = "2021"
authors = ["Thomas Ung"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = {version = "0.31.1", features = ["rand"]}

